"""Generate local Compose tokens. Run with material-color-utilities installed in Python."""

from pathlib import Path

from material_color_utilities import CustomColor, Variant, theme_from_color


SEEDS = {
    "Evergreen": "#22684B",
    "Indigo": "#6750A4",
    "Slate": "#35566E",
    "Clay": "#8F4C38",
}
ROLES = (
    "primary", "on_primary", "primary_container", "on_primary_container",
    "inverse_primary", "primary_fixed", "primary_fixed_dim", "on_primary_fixed",
    "on_primary_fixed_variant", "secondary", "on_secondary", "secondary_container",
    "on_secondary_container", "secondary_fixed", "secondary_fixed_dim",
    "on_secondary_fixed", "on_secondary_fixed_variant", "tertiary", "on_tertiary",
    "tertiary_container", "on_tertiary_container", "tertiary_fixed",
    "tertiary_fixed_dim", "on_tertiary_fixed", "on_tertiary_fixed_variant",
    "error", "on_error", "error_container", "on_error_container", "background",
    "on_background", "surface", "on_surface", "surface_variant",
    "on_surface_variant", "surface_dim", "surface_bright",
    "surface_container_lowest", "surface_container_low", "surface_container",
    "surface_container_high", "surface_container_highest", "inverse_surface",
    "inverse_on_surface", "outline", "outline_variant", "surface_tint", "scrim",
)


def camel(name):
    head, *tail = name.split("_")
    return head + "".join(piece.title() for piece in tail)


def color(value):
    return f"Color(0xFF{value[1:].upper()})"


out = [
    "package ph.notifly.ui.theme",
    "",
    "import androidx.compose.material3.ColorScheme",
    "import androidx.compose.material3.darkColorScheme",
    "import androidx.compose.material3.lightColorScheme",
    "import androidx.compose.ui.graphics.Color",
    "",
    "/** Generated by tools/generate_colors.py from the four original primary seeds.",
    " * Requires Python material-color-utilities; no runtime color dependency.",
    " * Material Color Utilities tonal spot, standard contrast, harmonized semantic colors.",
    " */",
    "enum class NotiflyPalette { Evergreen, Indigo, Slate, Clay }",
    "",
    "val NotiflyPalette.hint: String",
    '    get() = when (this) {',
    '        NotiflyPalette.Evergreen -> "Green"',
    '        NotiflyPalette.Indigo -> "Purple"',
    '        NotiflyPalette.Slate -> "Blue"',
    '        NotiflyPalette.Clay -> "Terracotta"',
    "    }",
    "",
    "data class NotiflyAccents(",
    "    val income: Color, val incomeContainer: Color, val onIncomeContainer: Color,",
    "    val expense: Color, val expenseContainer: Color, val onExpenseContainer: Color,",
    ")",
    "",
]
for name, seed in SEEDS.items():
    theme = theme_from_color(
        seed, 0.0, Variant.TONALSPOT,
        [CustomColor("#1E6B45", "income", True),
         CustomColor("#BA1A1A", "expense", True)],
    )
    for mode in ("light", "dark"):
        scheme = getattr(theme.schemes, mode)
        out.append(f"private val {name}{mode.title()} = {mode}ColorScheme(")
        for role in ROLES:
            # on_background is the same neutral role as on_surface in this utility release.
            value = getattr(scheme, role, None)
            if value is None and role == "on_background":
                value = scheme.on_surface
            out.append(f"    {camel(role)} = {color(value)},")
        out.append(")")
        out.append("")
        custom = {c.dict()["color"]["name"]: c.dict()[mode] for c in theme.custom_colors}
        out.append(f"private val {name}{mode.title()}Accents = NotiflyAccents(")
        for kind in ("income", "expense"):
            for role in ("color", "color_container", "on_color_container"):
                out.append(f"    {color(custom[kind][role])},")
        out.append(")")
        out.append("")

out += [
    "internal fun schemeFor(palette: NotiflyPalette, dark: Boolean = false): ColorScheme =",
    "    when (palette) {",
]
for name in SEEDS:
    out.append(f"        NotiflyPalette.{name} -> if (dark) {name}Dark else {name}Light")
out += [
    "    }",
    "",
    "internal fun accentsFor(palette: NotiflyPalette, dark: Boolean = false): NotiflyAccents =",
    "    when (palette) {",
]
for name in SEEDS:
    out.append(f"        NotiflyPalette.{name} -> if (dark) {name}DarkAccents else {name}LightAccents")
out += ["    }", ""]

Path("shared/src/commonMain/kotlin/ph/notifly/ui/theme/Color.kt").write_text(
    "\n".join(out), encoding="utf-8"
)
