"""Generate local Compose tokens. Run with material-color-utilities installed in Python."""

from pathlib import Path

from material_color_utilities import CustomColor, Variant, theme_from_color


SEEDS = {
    "Ube": "#7443E6",
    "Evergreen": "#22684B",
    "Slate": "#35566E",
    "Clay": "#8F4C38",
}
ROLES = (
    "primary", "on_primary", "primary_container", "on_primary_container",
    "inverse_primary", "primary_fixed", "primary_fixed_dim", "on_primary_fixed",
    "on_primary_fixed_variant", "secondary", "on_secondary", "secondary_container",
    "on_secondary_container", "secondary_fixed", "secondary_fixed_dim",
    "on_secondary_fixed", "on_secondary_fixed_variant", "tertiary", "on_tertiary",
    "tertiary_container", "on_tertiary_container", "tertiary_fixed",
    "tertiary_fixed_dim", "on_tertiary_fixed", "on_tertiary_fixed_variant",
    "error", "on_error", "error_container", "on_error_container", "background",
    "on_background", "surface", "on_surface", "surface_variant",
    "on_surface_variant", "surface_dim", "surface_bright",
    "surface_container_lowest", "surface_container_low", "surface_container",
    "surface_container_high", "surface_container_highest", "inverse_surface",
    "inverse_on_surface", "outline", "outline_variant", "surface_tint", "scrim",
)
ACCENTS = (
    "income", "income_container", "on_income_container",
    "expense", "expense_container", "on_expense_container",
    "confirmed", "on_confirmed",
)
# Ube is the brand palette (docs/brand/ube.css): its roles are pinned to the
# identity's swatches rather than derived. Tertiary marks pending review, which the brand draws in
# lilac. Tonal spot fills whatever is not listed.
# Tonal spot rotates tertiary toward pink; Ube has one hue, so its fixed tertiary mirrors primary fixed.
UBE_TERTIARY_FIXED = {
    "tertiary_fixed": "#E9DDFF", "tertiary_fixed_dim": "#CFBDFE",
    "on_tertiary_fixed": "#201047", "on_tertiary_fixed_variant": "#4C3D75",
}
BRAND = {
    ("Ube", "dark"): {
        "primary": "#CBB6FF", "on_primary": "#26134A", "primary_container": "#3A1F66",
        "on_primary_container": "#F4F0F8", "inverse_primary": "#7443E6",
        "secondary_container": "#3A1F66", "on_secondary_container": "#CBB6FF",
        "tertiary": "#CBB6FF", "on_tertiary": "#26134A", "tertiary_container": "#3A1F66",
        "on_tertiary_container": "#F4F0F8", **UBE_TERTIARY_FIXED,
        "background": "#110D17", "on_background": "#F4F0F8", "surface": "#110D17",
        "on_surface": "#F4F0F8", "surface_variant": "#2D2439", "on_surface_variant": "#A39AB6",
        "surface_dim": "#110D17", "surface_container_lowest": "#0A0810",
        "surface_container_low": "#16111D", "surface_container": "#1A1422",
        "surface_container_high": "#221A2D", "surface_container_highest": "#2D2439",
        "inverse_surface": "#F4F0F8", "inverse_on_surface": "#110D17",
        "outline": "#6F6683", "outline_variant": "#3A2F4C", "surface_tint": "#CBB6FF",
        "income": "#CBB6FF", "income_container": "#3A1F66", "on_income_container": "#CBB6FF",
        "expense": "#F4F0F8", "expense_container": "#2D2439", "on_expense_container": "#F4F0F8",
        "confirmed": "#7443E6", "on_confirmed": "#F4F0F8",
    },
    ("Ube", "light"): {
        "primary": "#7443E6", "on_primary": "#F4F0F8", "primary_container": "#E8DEFF",
        "on_primary_container": "#26134A", "inverse_primary": "#CBB6FF",
        "secondary_container": "#E8DEFF", "on_secondary_container": "#3A1F66",
        "tertiary": "#7443E6", "on_tertiary": "#F4F0F8", "tertiary_container": "#E8DEFF",
        "on_tertiary_container": "#3A1F66", **UBE_TERTIARY_FIXED,
        "background": "#F4F0F8", "on_background": "#110D17", "surface": "#F4F0F8",
        "on_surface": "#110D17", "surface_variant": "#E4DCEC", "on_surface_variant": "#5F5675",
        "surface_bright": "#F4F0F8", "surface_container_lowest": "#FFFFFF",
        "surface_container_low": "#EEE8F4", "surface_container": "#E8E1F0",
        "surface_container_high": "#E2DAEB", "surface_container_highest": "#DBD2E6",
        "inverse_surface": "#221A2D", "inverse_on_surface": "#F4F0F8",
        "outline": "#7D6F97", "outline_variant": "#CEC4DC", "surface_tint": "#7443E6",
        "income": "#7443E6", "income_container": "#E8DEFF", "on_income_container": "#3A1F66",
        "expense": "#110D17", "expense_container": "#E2DAEB", "on_expense_container": "#110D17",
        "confirmed": "#7443E6", "on_confirmed": "#F4F0F8",
    },
}


def camel(name):
    head, *tail = name.split("_")
    return head + "".join(piece.title() for piece in tail)


def color(value):
    return f"Color(0xFF{value[1:].upper()})"


out = [
    "package ph.notifly.ui.theme",
    "",
    "import androidx.compose.material3.ColorScheme",
    "import androidx.compose.material3.darkColorScheme",
    "import androidx.compose.material3.lightColorScheme",
    "import androidx.compose.ui.graphics.Color",
    "",
    "/** Generated by tools/generate_colors.py from the palette seeds.",
    " * Requires Python material-color-utilities; no runtime color dependency.",
    " * Material Color Utilities tonal spot, standard contrast, harmonized semantic colors;",
    " * Ube pins its roles to the brand swatches.",
    " */",
    "enum class NotiflyPalette { Ube, Evergreen, Slate, Clay }",
    "",
    "val NotiflyPalette.hint: String",
    '    get() = when (this) {',
    '        NotiflyPalette.Ube -> "Violet"',
    '        NotiflyPalette.Evergreen -> "Green"',
    '        NotiflyPalette.Slate -> "Blue"',
    '        NotiflyPalette.Clay -> "Terracotta"',
    "    }",
    "",
    "/** [confirmed] fills the tick a user's confirmation earns; pending stays an outlined ring. */",
    "data class NotiflyAccents(",
    "    val income: Color, val incomeContainer: Color, val onIncomeContainer: Color,",
    "    val expense: Color, val expenseContainer: Color, val onExpenseContainer: Color,",
    "    val confirmed: Color, val onConfirmed: Color,",
    ")",
    "",
]
icon_roles = {}
for name, seed in SEEDS.items():
    theme = theme_from_color(
        seed, 0.0, Variant.TONALSPOT,
        [CustomColor("#1E6B45", "income", True),
         CustomColor("#BA1A1A", "expense", True)],
    )
    for mode in ("light", "dark"):
        scheme = getattr(theme.schemes, mode)
        brand = BRAND.get((name, mode), {})
        icon_roles[name, mode] = {role: brand.get(role, getattr(scheme, role)) for role in ("primary", "on_primary", "primary_container", "on_primary_container")}
        out.append(f"private val {name}{mode.title()} = {mode}ColorScheme(")
        for role in ROLES:
            # on_background is the same neutral role as on_surface in this utility release.
            value = getattr(scheme, role, None)
            if value is None and role == "on_background":
                value = scheme.on_surface
            out.append(f"    {camel(role)} = {color(brand.get(role, value))},")
        out.append(")")
        out.append("")
        custom = {c.dict()["color"]["name"]: c.dict()[mode] for c in theme.custom_colors}
        # Confirmed stays the saturated light-scheme primary in both modes, like the brand's ube tick.
        income, expense = custom["income"], custom["expense"]
        accents = {
            "income": income["color"], "income_container": income["color_container"],
            "on_income_container": income["on_color_container"],
            "expense": expense["color"], "expense_container": expense["color_container"],
            "on_expense_container": expense["on_color_container"],
            "confirmed": theme.schemes.light.primary, "on_confirmed": theme.schemes.light.on_primary,
        }
        out.append(f"private val {name}{mode.title()}Accents = NotiflyAccents(")
        for role in ACCENTS:
            out.append(f"    {color(brand.get(role, accents[role]))},")
        out.append(")")
        out.append("")

out += [
    "internal fun schemeFor(palette: NotiflyPalette, dark: Boolean = false): ColorScheme =",
    "    when (palette) {",
]
for name in SEEDS:
    out.append(f"        NotiflyPalette.{name} -> if (dark) {name}Dark else {name}Light")
out += [
    "    }",
    "",
    "internal fun accentsFor(palette: NotiflyPalette, dark: Boolean = false): NotiflyAccents =",
    "    when (palette) {",
]
for name in SEEDS:
    out.append(f"        NotiflyPalette.{name} -> if (dark) {name}DarkAccents else {name}LightAccents")
out += ["    }", ""]

Path("shared/src/commonMain/kotlin/ph/notifly/ui/theme/Color.kt").write_text(
    "\n".join(out), encoding="utf-8"
)

# Platform icons render outside Compose. Generated from the same final (including Ube) roles.
import xml.etree.ElementTree as ET

RES = Path("app/src/main/res")
ANDROID = "{http://schemas.android.com/apk/res/android}"
mark = ET.parse("shared/src/commonMain/composeResources/drawable/notifly_mark.xml").getroot().find("path")
path_data = mark.attrib[ANDROID + "pathData"]
foreground = '''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <!-- Preserve the existing 0.44 scale / 32dp offset and adaptive safe zone. -->
    <group android:scaleX="0.44" android:scaleY="0.44" android:translateX="32" android:translateY="32">
        <path android:strokeColor="@color/{color}" android:strokeWidth="16" android:strokeLineCap="round"
            android:strokeLineJoin="round" android:pathData="{path}" />
    </group>
</vector>
'''
adaptive = '''<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/{name}_background" />
    <foreground android:drawable="@drawable/{name}_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
'''
colors = {"values": {}, "values-night": {}}
for palette in SEEDS:
    for mode in ("system", "light", "dark"):
        name = f"ic_launcher_{palette.lower()}_{mode}"
        for qualifier in colors:
            dark = mode == "dark" or (mode == "system" and qualifier == "values-night")
            roles = icon_roles[palette, "dark" if dark else "light"]
            colors[qualifier][name + "_background"] = roles["primary_container" if dark else "primary"]
            colors[qualifier][name + "_mark"] = roles["on_primary_container" if dark else "on_primary"]
        (RES / "drawable" / (name + "_foreground.xml")).write_text(
            foreground.format(color=name + "_mark", path=path_data), encoding="utf-8")
        (RES / "mipmap-anydpi" / (name + ".xml")).write_text(adaptive.format(name=name), encoding="utf-8")
for qualifier, entries in colors.items():
    folder = RES / qualifier
    folder.mkdir(exist_ok=True)
    (folder / "colors.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/generate_colors.py. Launcher only. -->\n<resources>\n'
        + "".join(f'    <color name="{name}">#FF{value[1:].upper()}</color>\n' for name, value in entries.items())
        + "</resources>\n", encoding="utf-8")
(RES / "drawable/ic_launcher_monochrome.xml").write_text(
    foreground.format(color="android:color/white", path=path_data).replace("@color/android:", "@android:"), encoding="utf-8")
(RES / "mipmap-anydpi/ic_launcher.xml").write_text(adaptive.format(name="ic_launcher_ube_system"), encoding="utf-8")
